create table public.export_audit_events (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete restrict,
  client_id uuid not null references public.profiles(id) on delete restrict,
  export_type text not null check (export_type in ('routine_pdf', 'progress_pdf', 'client_archive')),
  routine_id uuid references public.routines(id) on delete set null,
  period_start date,
  period_end date,
  anonymized boolean not null default false,
  result text not null check (result in ('completed', 'failed')),
  approximate_size_bytes bigint check (approximate_size_bytes is null or approximate_size_bytes >= 0),
  created_at timestamptz not null default now(),
  constraint export_audit_period_check check (
    (period_start is null and period_end is null)
    or (period_start is not null and period_end is not null and period_start <= period_end)
  )
);

create index export_audit_events_requester_created_idx
  on public.export_audit_events (requester_id, created_at desc);
create index export_audit_events_client_created_idx
  on public.export_audit_events (client_id, created_at desc);
create index export_audit_events_routine_idx
  on public.export_audit_events (routine_id)
  where routine_id is not null;

alter table public.export_audit_events enable row level security;

revoke all on public.export_audit_events from anon;
grant select, insert on public.export_audit_events to authenticated;
grant usage, select on sequence public.export_audit_events_id_seq to authenticated;

create policy export_audit_select_authorized
on public.export_audit_events for select to authenticated
using (
  requester_id = (select auth.uid())
  or client_id = (select auth.uid())
  or (select private.is_admin())
);

create policy export_audit_insert_authorized
on public.export_audit_events for insert to authenticated
with check (
  requester_id = (select auth.uid())
  and (
    client_id = (select auth.uid())
    or (select private.is_admin())
    or (select private.is_active_trainer_of(client_id))
  )
);

comment on table public.export_audit_events is
  'Metadata-only audit trail for generated exports. Exported content is never stored here.';
